default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') {'postgres'} %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') {''} %>
  port: <%= ENV.fetch('POSTGRES_PORT') {'5432'} %>

development:
  <<: *default
  database: portal_api_development

test:
  <<: *default
  database: portal_api_test

production:
  <<: *default
  database: portal_api_production

homolog:
  <<: *default
  database: portal_api_homolog
